apiVersion: v1
kind: Pod
metadata:
  name: build
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/notify.json
  restartPolicy: Never
  containers:
  - name: build
    image: docker.io/haih/build:latest
    imagePullPolicy: Always
    command: ["sh"]
    args: ["-c", "sleep infinity"]
