apiVersion: v1
kind: Pod
metadata:
  name: netperf
  namespace: default
  labels:
    run: netperf
spec:
  restartPolicy: Never
  containers:
  - name: netperf
    image: docker.io/networkstatic/netperf
    command: ["sh"]
    args: ["-c", "sleep infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: netserver
  namespace: default
  labels:
    run: netserver
spec:
  restartPolicy: Never
  containers:
  - name: netserver
    image: docker.io/networkstatic/netserver
    command: ["netserver"]
    args: ["-4", "-D", "-p", "1234"]
---
apiVersion: v1
kind: Service
metadata:
  name: netserver
  namespace: default
spec:
  selector:
    run: netserver
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
