apiVersion: v1
kind: Pod
metadata:
  name: mynotifypod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/notify.json
  restartPolicy: Never
  containers:
  - name: container1
    image: docker.io/haih/notify:latest
    command: ["sh"]
    args: ["-c", "sleep infinity"]
