apiVersion: v1
kind: Pod
metadata:
  name: open-s
spec:
  restartPolicy: Never
  hostPID: true
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/notify.json
  containers:
  - name: open-s
    image: docker.io/haih/open:latest
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
          - SYS_PTRACE
          - PERFMON
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - name: sysfs
      mountPath: /sys
    - name: perf
      mountPath: /proc
  volumes:
  - name: sysfs
    hostPath:
      path: /sys
  - name: perf
    hostPath:
      path: /proc
