apiVersion: v1
kind: Namespace
metadata:
  name: seccomp-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seccomp-agent
  namespace: seccomp-agent
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: seccomp-agent
subjects:
- kind: ServiceAccount
  name: seccomp-agent
  namespace: seccomp-agent
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccomp-agent
  namespace: seccomp-agent
  labels:
    k8s-app: seccomp-agent
spec:
  selector:
    matchLabels:
      k8s-app: seccomp-agent
  template:
    metadata:
      labels:
        k8s-app: seccomp-agent
    spec:
      serviceAccount: seccomp-agent
      hostPID: true
      containers:
      - name: seccomp-agent
        image: docker.io/haih/spireseccompagent:latest
        command: [ "/bin/seccompagent", "-resolver=kubernetes", "-log=info" ]
        #command: [ "/bin/seccompagent", "-resolver=kubernetes", "-log=trace" ]
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          # We need to keep 'privileged' to opt out of cgroupns, so we can
          # inspect containers' cgroups via their /proc/$pid/cgroup files.
          privileged: true
          capabilities:
            add:
            # CAP_SYS_PTRACE is useful to read arguments of a processes with
            # the prctl PR_SET_DUMPABLE bit set to zero.
            - "SYS_PTRACE"
            # CAP_SYS_ADMIN is useful to setns in containers and mount
            - "SYS_ADMIN"
            - "NET_ADMIN"
          # privileged: true
        volumeMounts:
        - name: seccomp-policies
          mountPath: /host/seccomp
        - name: run
          mountPath: /run
        # the freezer handler needs write access to the cgroup filesystems to
        # write "FROZEN" on "freezer.state" interface file.
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: spire-agent-socket
          mountPath: /run/spire/agent-sockets
          readOnly: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: seccomp-policies
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/agent-sockets
          type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists

