apiVersion: v1
kind: Pod
metadata:
  name: openssl-client
spec:
  restartPolicy: Never
  containers:
  - name: openssl-client
    image: finalgene/openssh
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    #command: ["sh"]
    #args: ["-c", "openssl s_client -connect openssl-svc:3000 -CAfile /tmp/bundle.0.pem -cert /tmp/svid.0.pem -key /tmp/svid.0.key -state"]
